Repository createmeal/createmeal, pull requests merged in 2022-02, with the labels that each got.

#32 Feature/refactoring node factory
  src/composite/NodeFactory.js
  src/index.js
Labels: enhancement

#35 Feature/option
  .vscode/launch.json
  src/composite/NodeFactory.js
  src/index.js
  test/test_option.js
Labels: enhancement

#40 issue 38: add check to ensure that null values bypassed and converted…
  src/composite/NodeFactory.js
  test/estruturaBasica.js
Labels: bug

#41 building v1.3.1
  dist/createmeal-legacy.js
  dist/createmeal.js
Labels: bug

#42 updating documentation
  README.html
  README.md
  documentation/readme-generator.js
  package.json
Labels: documentation

#48 substituing startswith in attributeFactory
  src/composite/AttributeFactory.js
Labels: enhancement

#64 Test every tag
  src/tags.js
  test/test_tag.js
Labels: enhancement
